export const AppColors = {
  background: '#F7F6F3',
  surface: '#FFFFFF',
  surfaceSoft: '#FBFAF8',
  border: '#ECEAE5',
  textPrimary: '#201F1C',
  textSecondary: '#8A867D',
  textMuted: '#B4B0A6',
  primary: '#6C5CE7',
  primarySoft: '#EFECFD',
  success: '#1FAE7A',
  successSoft: '#E6F7F0',
  warning: '#E0A21A',
  warningSoft: '#FBF2DE',
  danger: '#E0525C',
  dangerSoft: '#FBE9EA',
  info: '#2F9BD6',
  infoSoft: '#E6F3FB',
  teal: '#14B8A6',
  tealSoft: '#E1F7F4',
};